title: Quinn Perian
profile_img: /assets/img/headshot.jpg
icon_img: /assets/img/icon.webp

name: "Quinn Perian"
job: "Student at Masachusetts Institute of Technology"

linkedin_username: quinn-perian-a13120206
github_username: github

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag